### ISSUE TITLE
fails to build with lsp-2.8

### ISSUE THREAD

**Issue by juhp** [fizruk/rzk#220]
```
       Building library for rzk-0.7.7...
       [19 of 21] Compiling Language.Rzk.VSCode.Env
       /home/curators/work/unpack-dir/unpacked/rzk-0.7.7-b1ef46f9872d5360b922e7660235203a843c896be9461dce9dd64dc9e4d22022/src/Language/Rzk/VSCode/Env.hs:27:17: error: [GHC-87543]
           Ambiguous occurrence ‘ServerConfig’.
           It could refer to
              either ‘Language.LSP.Server.ServerConfig’,
                     imported from ‘Language.LSP.Server’ at src/Language/Rzk/VSCode/Env.hs:5:1-36
                     (and originally defined in ‘lsp-2.8.0.0:Language.LSP.Server.Control’),
                  or ‘Language.Rzk.VSCode.Config.ServerConfig’,
                     imported from ‘Language.Rzk.VSCode.Config’ at src/Language/Rzk/VSCode/Env.hs:7:46-57.
          |
       27 | type LSP = LspT ServerConfig (ReaderT RzkEnv IO)
          |                 ^^^^^^^^^^^^
```

**Comment by alaendle** [comment]
Guess this could be closed.
